export class Alumno {
    idAl:number;
    tipoDocAl:string;
    numDocAl:string;
    idRpr1:number;
    idRpr2:number;
    primNombAl:string;
    segNombAl:string;
    primApellAl:string;
    segApellAl:string;
    sexoAl:string;
    fechNacAl:string;
    edadAl:number;
    dirPpalAl:string;
    dirSecAl:string;
    tlfPpalAl:string;
    tlfSecAl:string;
    emailAl:string;
    fechIngAl:string;
}
